pdd_tvoy_gorod/urls.py
from django.urls import re_path
from django.conf.urls import include
from django.contrib import admin

urlpatterns = [
    re_path(r"^admin/", admin.site.urls),
    re_path(r'^', include('tutorial.urls')),
]

tutorial/urls.py
from django.urls import re_path,  include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^error$', views.error, name='error'),
    re_path(r'^tickets$', views.TicketListView.as_view(), name='tickets'),
    re_path(r'^ticket/(?P<pk>\d+)$', views.TicketDetailView.as_view(), name='ticket'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutorial/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from .files import image_upload, thumb_upload, create_thumbnail

class Ticket(models.Model):
    number = models.IntegerField(_("Номер билета"), unique=True, primary_key=True)
    question = models.TextField(_("Вопрос"), max_length=2000, help_text="Вопрос")
    choice1 = models.CharField(_("Вариант #1"), max_length=240, help_text="Вариант ответа")
    choice2 = models.CharField(_("Вариант #2"), max_length=240, help_text="Вариант ответа")
    choice3 = models.CharField(_("Вариант #3"), max_length=240, help_text="Вариант ответа")
    answer  = models.IntegerField(_("Номер правильного ответа"))
    image = models.ImageField(_("Изображение"), upload_to=image_upload, null=True, blank=True)
    thumbnail = models.ImageField(_("Превью"), upload_to=thumb_upload, null=True, blank=True)


    class Meta:
        ordering = ['number']

    def save(self, *args, **kwargs):
        adding = self._state.adding
        if adding:
            self.thumbnail = create_thumbnail(self.image)

        super().save(*args, **kwargs)

    def delete(self):
        for f in (self.image, self.thumbnail):
            f.delete(False)
        super().delete()

    def get_absolute_url(self):
        return reverse('ticket', args=[str(self.number)])

    def __str__(self):
        return 'Билет №'+str(self.number)


class Photo(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, related_name="photos")
    photo = models.ImageField(_("Фотография"), upload_to=image_upload)
    thumbnail = models.ImageField(_("Превью"), upload_to=thumb_upload, null=True, blank=True)

    def save(self, *args, **kwargs):
        adding = self._state.adding
        if adding:
            self.thumbnail = create_thumbnail(self.photo)

        super().save(*args, **kwargs)

    def delete(self):
        for f in (self.photo, self.thumbnail):
            f.delete(False)
        super().delete()

    def get_absolute_url(self):
        return reverse('ticket', args=[str(self.ticket)])

    def __str__(self):
        return str(self.photo)

tutorial/views.py
from django.shortcuts import render
from django.views import generic

from django.conf import settings
from .models import Ticket


def render_simple_page(request, page_name, title):
    return render(
        request,
        'pages/'+page_name+'.html',
        context={'menu_links': settings.MENU_LINKS, 'title': title }
    )

def index(request):
    return render_simple_page(request, 'index', settings.SITE_NAME)

def error(request):
    return render_simple_page(request, 'index', "Заглушка")

class TicketListView(generic.ListView):
    model = Ticket
    template_name = 'pages/tickets.html'

    def get_context_data(self, **kwargs):
        context = super(TicketListView, self).get_context_data(**kwargs)
        context['menu_links'] = settings.MENU_LINKS
        context['title'] = 'Билеты'
        return context

class TicketDetailView(generic.DetailView):
    model = Ticket
    template_name = 'pages/ticket.html'

    def get_context_data(self, **kwargs):
        context = super(TicketDetailView, self).get_context_data(**kwargs)
        context['menu_links'] = settings.MENU_LINKS
        context['title'] = self.__str__
        return context

templates/base_generic.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{{ title }}</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" href="{% static 'img/favicon.svg' %}" sizes="any" type="image/svg+xml">
	<link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/icon type">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	<script src="{% static 'js/main.js' %}"></script>
</head>

<body class="body">
	{% include 'header.html' %}
	<main class="main body__item">{% block main %}{% endblock %}</main>
	{% include 'footer.html' %}
</body>
</html>

templates/footer.html
<footer class="footer body__item">
    <a href="{% url 'error' %}">О нас</a>
</footer>

templates/header.html
<header class="header body__item">
    {% include 'menu.html' %}
    <a href="/admin">Админка</a>
</header>

templates/menu.html
<nav class="menu">
    {% for key, value in menu_links.items %}
        {% if key == 'index' %}
            <header class="menu__header">
                <a href="{% url key %}" class="menu__link">{{ value }}</a>
            </header>
        {% else %}
            <a href="{% url key %}"
               class="menu__link{% if key == request.path|cut:'/' %} menu__link_active{% endif %}">
                {{ value }}
            </a>
        {% endif %}
    {% endfor %}
</nav>

templates/pages/index.html
{% extends "base_generic.html" %}

{% block main %}
    <a href="tickets">Перейти к билетам -></a>
{% endblock %}

templates/pages/ticket.html
{% extends "base_generic.html" %}

{% block main %}
    <article class="ticket">
        <h2 class="ticket__title">{{ ticket }}</h2>
        {% if ticket.image %}
            <img src="{{ ticket.image.url }}" class="ticket__image">
        {% else %}
            <p class="ticket__image-empty">Изображения нет.</p>
        {% endif %}
        {% if ticket.photos %}
            <div class="ticket__photos">
                {% for image in ticket.photos.all %}
                    <a target="_blank" href="{{ image.photo.url }}">
                        <img src="{{ image.thumbnail.url }}">
                    </a>
                {% endfor %}
            </div>
        {% endif %}
        <p class="ticket__question">{{ ticket.question }}</p>
        <p class="choice">{{ ticket.choice1 }}</p>
        <p class="choice">{{ ticket.choice2 }}</p>
        <p class="choice">{{ ticket.choice3 }}</p>
{% endblock %}

templates/pages/tickets.html
{% extends "base_generic.html" %}

{% block main %}
    {% for ticket in ticket_list %}
        <a href="{{ ticket.get_absolute_url }}">{{ ticket }}</a>
    {% empty %}
        <span class="empty">Не найдено ни одно билета.</span>
    {% endfor %}
    {{ tickets_list }}
{% endblock %}